version: '3'
services:

  node:
    image: julianomiranda/nodefull
    container_name: node
    restart: unless-stopped
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./node:/urs/src/app
    links:
      - db
    depends_on:
      - db
    networks:
      - node-network
      
  db:
    image: mysql:8.0
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql8
    environment:
#      - MYSQL_USER=root
      - MYSQL_DATABASE=nodedb
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
      
  nginx:
    restart: unless-stopped
    image: nginx
    ports:
      - "8080:80"
    depends_on:
      - node
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - node-network
networks:
  node-network:
    driver: bridge